export const styles = {
  startNode: {
    width: 70,
    height: 70,
    borderRadius: "50%",
    backgroundColor: "#8ab86e",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "white",
    border: "2px solid #8ab86e",
    fontWeight: "bold",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
  endNode: {
    width: 70,
    height: 70,
    borderRadius: "50%",
    backgroundColor: "#e35b5b",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "white",
    border: "2px solid #e35b5b",
    fontWeight: "bold",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
  genericNode: {
    width: 300,
    height: 64,
    borderRadius: "8px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #849E4C",
    borderWidth: "1px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    position: "relative" as const,
  },
  nodeContent: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
    padding: "0 15px",
  },
  deleteButton: {
    color: "#ff4d4f",
    padding: "2px",
  }
}; 